# Generated by Django 5.0.6 on 2024-07-27 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='takers',
            field=models.ManyToManyField(blank=True, related_name='taken_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
